package AddButtonItems;

import Mainpackage.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class addStaffInfoPanel extends javax.swing.JFrame {

    /**
     * Creates new form addVisitorInfoPanel
     */
    public addStaffInfoPanel() {
        initComponents();
        //setting the login screen in the middle of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staffNameField = new javax.swing.JTextField();
        staffPhoneField = new javax.swing.JTextField();
        staffSexField = new javax.swing.JComboBox<>();
        staffAgeField = new javax.swing.JTextField();
        staffAddressField = new javax.swing.JTextField();
        staffDesignationField = new javax.swing.JTextField();
        staffHireDateField = new javax.swing.JTextField();
        staffRegionField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff's Information");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 64, 175));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 450));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staffNameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 210, 30));

        staffPhoneField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, 30));

        staffSexField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        staffSexField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(staffSexField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, 30));

        staffAgeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, 30));

        staffAddressField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 210, 30));

        staffDesignationField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffDesignationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 210, 30));

        staffHireDateField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffHireDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 210, 30));

        staffRegionField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(staffRegionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 210, 30));

        confirmButton.setBackground(new java.awt.Color(65, 40, 107));
        confirmButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, -1));

        cancelButton.setBackground(new java.awt.Color(65, 40, 107));
        cancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, -1, -1));

        jPanel2.setBackground(new java.awt.Color(49, 30, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 430));

        jPanel3.setBackground(new java.awt.Color(49, 30, 81));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 10, 430));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Staff's Age");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Staff's Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Staff's Working Region");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Staff's Sex");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, 20));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Staff's Phone");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Staff's Address");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 20));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Staff's Designation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, 20));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Staff's Hire Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //will close the additem's window
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //creating database object
        DatabaseConnection dbc = new DatabaseConnection();

        try {
            //checking if the field's are empty or not
            InvalidInputExceptions iie = new InvalidInputExceptions();
            if (iie.checkIfEmptyField(staffNameField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Name");
            }
            if (iie.checkIfEmptyField(staffPhoneField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Phone Number");
            }
            if (iie.checkIfEmptyField(staffAgeField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Age");
            }
            if (iie.checkIfEmptyField(staffAddressField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Address");
            }
            if (iie.checkIfEmptyField(staffDesignationField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Designation");
            }
            if (iie.checkIfEmptyField(staffHireDateField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Hiredate");
            }
            if (iie.checkIfEmptyField(staffRegionField.getText()) == true) {
                throw new InvalidInputExceptions("Input Staff's Region");
            }

            //checking if name is valid or not
            if (iie.checkIfInvalidName(staffNameField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid staff's Name");
            }

            //checking if phone is valid or not
            if (iie.checkIfInvalidPhone(staffPhoneField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid staff's Phone Number");
            }

            //checking if Age is valid or not
            if (iie.checkIfInvalidAge(staffAgeField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid staff's Age");
            }

            //inserting values to database
            //  .trim()  is used for removing whitespace in the beginning and the ending of a string
            //  .replaceAll("\\s+","")  is used for removing characters in between whitespace
            String addvisitorinfoquery = "insert into Staff_Info (staff_name,staff_phone,staff_gender,staff_age,staff_address,staff_designation,staff_hiredate,region_no) values(?,?,?,?,?,?,?,?)";
            PreparedStatement pst = dbc.preparedStatementQuery(addvisitorinfoquery);
            pst.setString(1, staffNameField.getText().trim());
            pst.setString(2, staffPhoneField.getText().trim().replaceAll("\\s+", ""));
            String staff_sex = staffSexField.getSelectedItem().toString();
            pst.setString(3, staff_sex);
            pst.setString(4, staffAgeField.getText().trim().replaceAll("\\s+", ""));
            pst.setString(5, staffAddressField.getText().trim());
            pst.setString(6, staffDesignationField.getText().trim());
            pst.setString(7, staffHireDateField.getText().trim());
            pst.setString(8, staffRegionField.getText().trim().replaceAll("\\s+", ""));
             
            
            pst.executeUpdate();

            //showing insertion successful
            JOptionPane.showMessageDialog(null, "Staff's Information inserted successfully !");

            //disposing the additems panel
            dispose();
        } catch (InvalidInputExceptions e) {
            //catches the user defined input exception
            JOptionPane.showMessageDialog(null, e);

        } catch (Exception e) {
            //catches all other exceptions
            JOptionPane.showMessageDialog(null, e);
        }
        //closing database connection
        dbc.dbClose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStaffInfoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField staffAddressField;
    private javax.swing.JTextField staffAgeField;
    private javax.swing.JTextField staffDesignationField;
    private javax.swing.JTextField staffHireDateField;
    private javax.swing.JTextField staffNameField;
    private javax.swing.JTextField staffPhoneField;
    private javax.swing.JTextField staffRegionField;
    private javax.swing.JComboBox<String> staffSexField;
    // End of variables declaration//GEN-END:variables
}
