package AddButtonItems;

import Mainpackage.*;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class addVisitorInfoPanel extends javax.swing.JFrame {

    /**
     * Creates new form addVisitorInfoPanel
     */
    public addVisitorInfoPanel() {
        initComponents();
        //setting the login screen in the middle of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        visitorNameField = new javax.swing.JTextField();
        visitorPhoneField = new javax.swing.JTextField();
        visitorAgeField = new javax.swing.JTextField();
        visitorSexField = new javax.swing.JComboBox<>();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitor's Information");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(105, 64, 175));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visitorNameField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        visitorNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(visitorNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, 30));

        visitorPhoneField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        visitorPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorPhoneFieldActionPerformed(evt);
            }
        });
        jPanel1.add(visitorPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 210, 30));

        visitorAgeField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(visitorAgeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 210, 30));

        visitorSexField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        visitorSexField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(visitorSexField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 90, 30));

        confirmButton.setBackground(new java.awt.Color(65, 40, 107));
        confirmButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        confirmButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        jPanel1.add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        cancelButton.setBackground(new java.awt.Color(65, 40, 107));
        cancelButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jPanel2.setBackground(new java.awt.Color(49, 30, 81));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 10, 380));

        jPanel3.setBackground(new java.awt.Color(49, 30, 81));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visitor's Sex");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Visitor's Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Visitor's Phone ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visitor's Age");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        //will close the additem's window
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        //creating database object
        DatabaseConnection dbc = new DatabaseConnection();

        try {
            //checking if the field's are empty or not
            InvalidInputExceptions iie = new InvalidInputExceptions();
            if (iie.checkIfEmptyField(visitorNameField.getText()) == true) {
                throw new InvalidInputExceptions("Input Visitor's Name");
            }
            if (iie.checkIfEmptyField(visitorPhoneField.getText()) == true) {
                throw new InvalidInputExceptions("Input Visitor's Phone Number");
            }
            if (iie.checkIfEmptyField(visitorAgeField.getText()) == true) {
                throw new InvalidInputExceptions("Input Visitor's Age");
            }

            //checking if name is valid or not
            if (iie.checkIfInvalidName(visitorNameField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid Visitor's Name");
            }

            //checking if phone is valid or not
            if (iie.checkIfInvalidPhone(visitorPhoneField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid Visitor's Phone Number");
            }

            //checking if Age is valid or not
            if (iie.checkIfInvalidAge(visitorAgeField.getText()) == true) {
                throw new InvalidInputExceptions("Invalid Visitor's Age");
            }

            //inserting values to database
            //  .trim()  is used for removing whitespace in the beginning and the ending of a string
            //  .replaceAll("\\s+","")  is used for removing characters in between whitespace
            String addvisitorinfoquery = "insert into Visitor_Info (visitor_name,visitor_phone,visitor_age,visitor_gender) values(?,?,?,?)";
            PreparedStatement pst = dbc.preparedStatementQuery(addvisitorinfoquery);
            pst.setString(1, visitorNameField.getText().trim());
            pst.setString(2, visitorPhoneField.getText().trim().replaceAll("\\s+", ""));
            pst.setString(3, visitorAgeField.getText().trim().replaceAll("\\s+", ""));
            String visitor_sex = visitorSexField.getSelectedItem().toString();
            pst.setString(4, visitor_sex);
            pst.executeUpdate();

            //showing insertion successful
            JOptionPane.showMessageDialog(null, "Visitor's Information inserted successfully !");

            //disposing the additems panel
            dispose();
        } catch (InvalidInputExceptions e) {
            //catches the user defined input exception
            JOptionPane.showMessageDialog(null, e);

        } catch (Exception e) {
            //catches all other exceptions
            JOptionPane.showMessageDialog(null, e);
        }
        //closing database connection
        dbc.dbClose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void visitorNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorNameFieldActionPerformed

    private void visitorPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorPhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_visitorPhoneFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVisitorInfoPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField visitorAgeField;
    private javax.swing.JTextField visitorNameField;
    private javax.swing.JTextField visitorPhoneField;
    private javax.swing.JComboBox<String> visitorSexField;
    // End of variables declaration//GEN-END:variables
}
