package SearchButtonItems;

import Mainpackage.*;
import MenuItems.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Getter method's class for Visitor Info
class VisitorInfoModel {

    private int visitor_id, visitor_age;
    private String visitor_name, visitor_phone, visitor_gender;

    public VisitorInfoModel(int visitor_id, String visitor_name, String visitor_phone, String visitor_gender, int visitor_age) {
        this.visitor_id = visitor_id;
        this.visitor_name = visitor_name;
        this.visitor_phone = visitor_phone;
        this.visitor_gender = visitor_gender;
        this.visitor_age = visitor_age;
    }

    public int getvisitor_id() {
        return visitor_id;
    }

    public String getvisitor_name() {
        return visitor_name;
    }

    public String getvisitor_phone() {
        return visitor_phone;
    }

    public String getvisitor_gender() {
        return visitor_gender;
    }

    public int getvisitor_age() {
        return visitor_age;
    }
}

public class searchVisitorInfoPanel extends javax.swing.JFrame {

    //variable declaration of query so that we can use it while passing into a method
    //query string is used in some method in this name: "qString". queryString must be static
    private static String queryString;

    public void setQueryString(String qString) {
        this.queryString = qString;
    }

    //Array List for retrieving info from database
    //qString is the String of Query operation
    private ArrayList<VisitorInfoModel> visitorList(String qString) {
        ArrayList<VisitorInfoModel> visitorsList = new ArrayList<>();
        DatabaseConnection dbc = new DatabaseConnection();
        try {
            ResultSet rs = dbc.resultSetQuery(qString);

            VisitorInfoModel visitor;
            while (rs.next()) {
                visitor = new VisitorInfoModel(rs.getInt("visitor_id"), rs.getString("visitor_name"), rs.getString("visitor_phone"), rs.getString("visitor_gender"), rs.getInt("visitor_age"));
                visitorsList.add(visitor);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return visitorsList;
    }

    //showing values from database to the jtable
    //qString is the String of Query operation
    private void showSearchedVisitorInfo(String qString) {
        ArrayList<VisitorInfoModel> list = visitorList(qString);
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getvisitor_id();
            row[1] = list.get(i).getvisitor_name();
            row[2] = list.get(i).getvisitor_phone();
            row[3] = list.get(i).getvisitor_gender();
            row[4] = list.get(i).getvisitor_age();

            model.addRow(row);
        }
    }

    /**
     * Creates new form searchVisitorInfoPanel
     */
    public searchVisitorInfoPanel(String queryString) {
        initComponents();
        //setting the screen in the middle of the screen
        setLocationRelativeTo(null);

        //shwoing the jtable with values
        showSearchedVisitorInfo(queryString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        tableScrollPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitor's Information");
        setMaximumSize(new java.awt.Dimension(530, 450));
        setMinimumSize(new java.awt.Dimension(530, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(654, 471));
        contentPanel.setMinimumSize(new java.awt.Dimension(654, 471));
        contentPanel.setLayout(null);

        tableScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPanel.setForeground(new java.awt.Color(255, 255, 255));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Sex", "Age"
            }
        ));
        tableScrollPanel.setViewportView(dataTable);

        contentPanel.add(tableScrollPanel);
        tableScrollPanel.setBounds(10, 90, 510, 300);

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Result");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(10, 30, 510, 30);

        jPanel1.setBackground(new java.awt.Color(65, 40, 107));
        jPanel1.setLayout(null);
        contentPanel.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 10);

        jPanel2.setBackground(new java.awt.Color(65, 40, 107));
        jPanel2.setLayout(null);
        contentPanel.add(jPanel2);
        jPanel2.setBounds(10, 70, 510, 10);

        jPanel3.setBackground(new java.awt.Color(65, 40, 107));
        jPanel3.setLayout(null);
        contentPanel.add(jPanel3);
        jPanel3.setBounds(370, 30, 150, 30);

        jPanel4.setBackground(new java.awt.Color(65, 40, 107));
        jPanel4.setLayout(null);
        contentPanel.add(jPanel4);
        jPanel4.setBounds(10, 30, 150, 30);

        deleteButton.setBackground(new java.awt.Color(65, 40, 107));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        contentPanel.add(deleteButton);
        deleteButton.setBounds(420, 400, 90, 25);

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //choosing first column, the one, which is primary key
        int column = 0;
        int row = dataTable.getSelectedRow();
        String primKey = dataTable.getModel().getValueAt(row, column).toString();

        //preparing query string for delete
        String delQueryString = "DELETE FROM visitor_info WHERE visitor_id = '" + primKey + "'";

        //connecting db and then deleting the row according to primary key
        DatabaseConnection dbc = new DatabaseConnection();
        try {
            PreparedStatement pst = dbc.preparedStatementQuery(delQueryString);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted successfully");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        dbc.dbClose();
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchVisitorInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchVisitorInfoPanel(queryString).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
