/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuItems;
import UpdateButtonItems.*;
import AddButtonItems.*;
import Mainpackage.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;



//model class
class EntryTicketInfoModel{
    
    private String ticket_type;
    private int ticket_price;
    
    //constractor
    public EntryTicketInfoModel(String ticket_type, int ticket_price) {
        this.ticket_type = ticket_type;
        this.ticket_price = ticket_price;
    }

    //getters
    public String getTicket_type() {
        return ticket_type;
    }

    public int getTicket_price() {
        return ticket_price;
    }
    
}
/**
 *
 * @author Julfikar
 */
public class entryTicketInfoPanel extends javax.swing.JPanel {
    
    public String ticket_price;

    
    //variable declaration of query so that we can use it while passing into a method
    //query string is used in some method in this name: "qString"
    private String queryString = "SELECT * FROM Entry_Ticket_type";

    //Array List for retrieving info from database
    //qString is the String of Query operation
    private ArrayList<EntryTicketInfoModel> entryTicketList(String qString) {
        ArrayList<EntryTicketInfoModel> entryTickestList = new ArrayList<>();
        DatabaseConnection dbc = new DatabaseConnection();
        try {

            ResultSet rs = dbc.resultSetQuery(qString);

            EntryTicketInfoModel entryTicketInfo;
            while (rs.next()) {
                entryTicketInfo = new EntryTicketInfoModel(rs.getString("eticket_type"), rs.getInt("eticket_price"));
                entryTickestList.add(entryTicketInfo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return entryTickestList;
    }

    //showing values from database to the jtable
    //qString is the String of Query operation
    private void show_entryTicketInfo(String qString) {
        ArrayList<EntryTicketInfoModel> list = entryTicketList(qString);
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTicket_type();
            row[1] = list.get(i).getTicket_price();
            
            model.addRow(row);
        }
    }
    /**
     * Creates new form visitorInfoPanel
     */
    public entryTicketInfoPanel() {
        initComponents();
        show_entryTicketInfo(queryString);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tableScrollPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        addButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 51));
        setMaximumSize(new java.awt.Dimension(530, 450));
        setMinimumSize(new java.awt.Dimension(530, 450));
        setPreferredSize(new java.awt.Dimension(530, 450));
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(530, 500));
        contentPanel.setMinimumSize(new java.awt.Dimension(530, 500));
        contentPanel.setPreferredSize(new java.awt.Dimension(530, 500));
        contentPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(65, 40, 107));
        jPanel1.setLayout(null);
        contentPanel.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 10);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entry Ticket Information");
        contentPanel.add(jLabel1);
        jLabel1.setBounds(10, 30, 510, 30);

        jPanel2.setBackground(new java.awt.Color(65, 40, 107));
        jPanel2.setLayout(null);
        contentPanel.add(jPanel2);
        jPanel2.setBounds(10, 70, 510, 10);

        jPanel3.setBackground(new java.awt.Color(65, 40, 107));
        jPanel3.setLayout(null);
        contentPanel.add(jPanel3);
        jPanel3.setBounds(420, 30, 100, 30);

        jPanel4.setBackground(new java.awt.Color(65, 40, 107));
        jPanel4.setLayout(null);
        contentPanel.add(jPanel4);
        jPanel4.setBounds(10, 30, 100, 30);

        tableScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPanel.setForeground(new java.awt.Color(255, 255, 255));

        dataTable.setBackground(new java.awt.Color(255, 255, 255));
        dataTable.setForeground(new java.awt.Color(0, 0, 0));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Type", "Ticket Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPanel.setViewportView(dataTable);

        contentPanel.add(tableScrollPanel);
        tableScrollPanel.setBounds(10, 90, 510, 300);

        addButton.setBackground(new java.awt.Color(65, 40, 107));
        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Update");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        contentPanel.add(addButton);
        addButton.setBounds(310, 440, 110, 33);

        addButton1.setBackground(new java.awt.Color(65, 40, 107));
        addButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton1.setForeground(new java.awt.Color(255, 255, 255));
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });
        contentPanel.add(addButton1);
        addButton1.setBounds(440, 440, 80, 33);

        add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        //This will bring the frame which was implemented for add button into the screen in Nimbus look 
        int column = 0;
        int row = dataTable.getSelectedRow();
        String primKey = dataTable.getModel().getValueAt(row, column).toString();
        System.out.println(primKey);
        
        UpdateEntryTicketInfoPanel up = new UpdateEntryTicketInfoPanel(primKey);
        up.setPrim(primKey);
        //up.setPrim(primKey);
        System.out.println(primKey);
        
        String[] args = null;
        up.main(args);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        // TODO add your handling code here:
        String[] args = null;
        new addEntryTicketInfoPanel().main(args);
    }//GEN-LAST:event_addButton1ActionPerformed

    
    public void mouseClicked(MouseEvent e) {
 
        System.out.println(e.toString());
        int i = dataTable.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        
         // Display Slected Row In JTexteFields
        ticket_price = (model.getValueAt(i,0).toString());
        System.out.println(ticket_price);

       // jTextField_FirstName.setText(model.getValueAt(i,1).toString());

       

    }

    
    public String getTicketPrice()
    {
        System.out.println(ticket_price);
        return ticket_price;
          
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
