package MenuItems;

import AddButtonItems.addVisitorInfoPanel;
import Mainpackage.*;
import QueryInfo.*;
import SearchButtonItems.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

//Getter method's class for Visitor Info
class VisitorInfoModel {

    private int visitor_id, visitor_age;
    private String visitor_name, visitor_phone, visitor_gender;

    public VisitorInfoModel(int visitor_id, String visitor_name, String visitor_phone, String visitor_gender, int visitor_age) {
        this.visitor_id = visitor_id;
        this.visitor_name = visitor_name;
        this.visitor_phone = visitor_phone;
        this.visitor_gender = visitor_gender;
        this.visitor_age = visitor_age;
    }

    public int getvisitor_id() {
        return visitor_id;
    }

    public String getvisitor_name() {
        return visitor_name;
    }

    public String getvisitor_phone() {
        return visitor_phone;
    }

    public String getvisitor_gender() {
        return visitor_gender;
    }

    public int getvisitor_age() {
        return visitor_age;
    }
}

public class visitorInfoPanel extends javax.swing.JPanel {

    //variable declaration of query so that we can use it while passing into a method
    //query string is used in some method in this name: "qString"
    private String queryString = "SELECT * FROM Visitor_Info";

    //Array List for retrieving info from database
    //qString is the String of Query operation
    private ArrayList<VisitorInfoModel> visitorList(String qString) {
        ArrayList<VisitorInfoModel> visitorsList = new ArrayList<>();
        DatabaseConnection dbc = new DatabaseConnection();
        try {

            ResultSet rs = dbc.resultSetQuery(qString);

            VisitorInfoModel visitor;
            while (rs.next()) {
                visitor = new VisitorInfoModel(rs.getInt("visitor_id"), rs.getString("visitor_name"), rs.getString("visitor_phone"), rs.getString("visitor_gender"), rs.getInt("visitor_age"));
                visitorsList.add(visitor);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return visitorsList;
    }

    //showing values from database to the jtable
    //qString is the String of Query operation
    private void show_visitorInfo(String qString) {
        ArrayList<VisitorInfoModel> list = visitorList(qString);
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getvisitor_id();
            row[1] = list.get(i).getvisitor_name();
            row[2] = list.get(i).getvisitor_phone();
            row[3] = list.get(i).getvisitor_gender();
            row[4] = list.get(i).getvisitor_age();

            model.addRow(row);
        }
    }

    /**
     * Creates new form visitorInfoPanel
     */
    public visitorInfoPanel() {
        initComponents();

        //showing the jtable with values
        show_visitorInfo(queryString);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tableScrollPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchCategoryField = new javax.swing.JComboBox<>();
        searchButton = new javax.swing.JButton();
        searchValueField = new javax.swing.JTextField();
        infoButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 51));
        setMaximumSize(new java.awt.Dimension(530, 450));
        setMinimumSize(new java.awt.Dimension(530, 450));
        setPreferredSize(new java.awt.Dimension(530, 450));
        setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(530, 500));
        contentPanel.setMinimumSize(new java.awt.Dimension(530, 500));
        contentPanel.setPreferredSize(new java.awt.Dimension(530, 500));
        contentPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visitor's Information");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(10, 30, 510, 30);

        jPanel1.setBackground(new java.awt.Color(65, 40, 107));
        jPanel1.setLayout(null);
        contentPanel.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 10);

        jPanel2.setBackground(new java.awt.Color(65, 40, 107));
        jPanel2.setLayout(null);
        contentPanel.add(jPanel2);
        jPanel2.setBounds(10, 70, 510, 10);

        jPanel3.setBackground(new java.awt.Color(65, 40, 107));
        jPanel3.setLayout(null);
        contentPanel.add(jPanel3);
        jPanel3.setBounds(400, 30, 120, 30);

        jPanel4.setBackground(new java.awt.Color(65, 40, 107));
        jPanel4.setLayout(null);
        contentPanel.add(jPanel4);
        jPanel4.setBounds(10, 30, 120, 30);

        tableScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPanel.setForeground(new java.awt.Color(255, 255, 255));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Sex", "Age"
            }
        ));
        tableScrollPanel.setViewportView(dataTable);

        contentPanel.add(tableScrollPanel);
        tableScrollPanel.setBounds(10, 90, 510, 300);

        addButton.setBackground(new java.awt.Color(65, 40, 107));
        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        contentPanel.add(addButton);
        addButton.setBounds(440, 440, 80, 25);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search By:");
        contentPanel.add(jLabel1);
        jLabel1.setBounds(10, 390, 110, 40);

        searchCategoryField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        searchCategoryField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "ID", "Name", "Phone", "Sex", "Age" }));
        searchCategoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCategoryFieldActionPerformed(evt);
            }
        });
        contentPanel.add(searchCategoryField);
        searchCategoryField.setBounds(120, 400, 110, 30);

        searchButton.setBackground(new java.awt.Color(65, 40, 107));
        searchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        contentPanel.add(searchButton);
        searchButton.setBounds(330, 440, 90, 25);

        searchValueField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        contentPanel.add(searchValueField);
        searchValueField.setBounds(30, 440, 200, 30);

        infoButton.setText("Information");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });
        contentPanel.add(infoButton);
        infoButton.setBounds(329, 400, 190, 25);

        add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        //This will bring the frame which was implemented for add button into the screen in Nimbus look 
        String[] args = null;
        new addVisitorInfoPanel().main(args);
    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //getting "Search By" column name and value from the form
        
        
        
        
        
        String strCol = searchCategoryField.getSelectedItem().toString();
        String strVal = searchValueField.getText();

        //changing column name to database's column name
        if (strCol.equals("Sl.no".trim())) {
            strCol = "visitor_id";
        } else if (strCol.equals("Name".trim())) {
            strCol = "visitor_name";
        } else if (strCol.equals("Phone".trim())) {
            strCol = "visitor_phone";
        } else if (strCol.equals("Sex".trim())) {
            strCol = "visitor_gender";
        } else if (strCol.equals("Age".trim())) {
            strCol = "visitor_age";
        }

        try {
            if (strCol.equals("-")) {
                throw new InvalidInputExceptions("Choose a column to search.");
            }
            if (strVal.trim().equals("")) {
                throw new InvalidInputExceptions("Type a value to search.");
            }

            //setting up the query string
            queryString = "SELECT * FROM Visitor_Info WHERE " + strCol + " = " + "'" + strVal + "'";

            //This will bring the frame which was implemented for add button into the screen in Nimbus look 
            //passing query string through jframe form
            String[] args = null;
            searchVisitorInfoPanel ob = new searchVisitorInfoPanel(queryString);

            //setting query string to desired frame's variable
            ob.setQueryString(queryString);

            //setting visible the jframe
            ob.main(args);
        } catch (InvalidInputExceptions e) {
            //catches the user defined input exception
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchCategoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCategoryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchCategoryFieldActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
            String[] args = null;
            queryVisitorInfoPanel ob = new queryVisitorInfoPanel(queryString);
            ob.setQueryString(queryString);
            ob.main(args);
    }//GEN-LAST:event_infoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchCategoryField;
    private javax.swing.JTextField searchValueField;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
