package QueryInfo;
import MenuItems.*;
import AddButtonItems.addStaffInfoPanel;
import Mainpackage.*;
import SearchButtonItems.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import QueryInfo.*;



public class queryVisitorInfoPanel extends javax.swing.JFrame {
  
    private static String queryString;

    public  void setQueryString(String queryString) {
        queryVisitorInfoPanel.queryString = queryString;
    }
    
    
   
    
     
      private int queryAge1() {
        int queryAge1 = 0;
        DatabaseConnection dbc = new DatabaseConnection();
        String querykid = "SELECT COUNT (visitor_age) FROM Visitor_Info where visitor_age between 0 and 11";
        try {

            ResultSet rs = dbc.resultSetQuery(querykid);

       
            while (rs.next()) {
                queryAge1 = rs.getInt("Visitor_Info");
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return queryAge1 ;
    }
    
    private int queryAge2() {
        int queryAge2 = 0;
        DatabaseConnection dbc = new DatabaseConnection();
        String queryteen = "SELECT COUNT (visitor_age) FROM Visitor_Info where visitor_age between 0 and 11";
        try {

            ResultSet rs = dbc.resultSetQuery(queryteen);

       
            while (rs.next()) {
                queryAge2 = rs.getInt("visitor_age");
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return queryAge2 ;
    }
    
     private int queryAge3() {
        int queryAge3 = 0;
        DatabaseConnection dbc = new DatabaseConnection();
        String queryadult = "SELECT COUNT (visitor_age) FROM Visitor_Info where visitor_age between 0 and 11";
        try {

            ResultSet rs = dbc.resultSetQuery(queryadult);

       
            while (rs.next()) {
                queryAge3 = rs.getInt("Visitor_Info");
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return queryAge3 ;
    }
    
   

    private void show_VisitorInfo(String qString) {
       
        kidVisitor.setText(String.valueOf(queryAge1()));
        teenVisitor.setText(String.valueOf(queryAge2()));
        adultVisitor.setText(String.valueOf(queryAge3()));
        
    }

    public queryVisitorInfoPanel(String queryString) {
        initComponents();
        show_VisitorInfo(queryString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        contentPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        tableScrollPanel1 = new javax.swing.JScrollPane();
        dataTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        kidVisitor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        teenVisitor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adultVisitor = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jPanel5.setBackground(new java.awt.Color(102, 255, 51));
        jPanel5.setMaximumSize(new java.awt.Dimension(530, 500));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        contentPanel1.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel1.setMaximumSize(new java.awt.Dimension(530, 500));
        contentPanel1.setMinimumSize(new java.awt.Dimension(530, 500));
        contentPanel1.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(65, 40, 107));
        jPanel6.setLayout(null);
        contentPanel1.add(jPanel6);
        jPanel6.setBounds(10, 10, 510, 10);

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff's Information");
        contentPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 510, 30);

        jPanel7.setBackground(new java.awt.Color(65, 40, 107));
        jPanel7.setLayout(null);
        contentPanel1.add(jPanel7);
        jPanel7.setBounds(10, 70, 510, 10);

        jPanel8.setBackground(new java.awt.Color(65, 40, 107));
        jPanel8.setLayout(null);
        contentPanel1.add(jPanel8);
        jPanel8.setBounds(400, 30, 120, 30);

        jPanel9.setBackground(new java.awt.Color(65, 40, 107));
        jPanel9.setLayout(null);
        contentPanel1.add(jPanel9);
        jPanel9.setBounds(10, 30, 120, 30);

        tableScrollPanel1.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPanel1.setForeground(new java.awt.Color(255, 255, 255));

        dataTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Designation", "Hire Date", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPanel1.setViewportView(dataTable1);

        contentPanel1.add(tableScrollPanel1);
        tableScrollPanel1.setBounds(10, 90, 510, 130);
        contentPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 510, 100);

        jPanel5.add(contentPanel1, new java.awt.GridBagConstraints());

        setBackground(new java.awt.Color(102, 255, 51));
        setMinimumSize(new java.awt.Dimension(530, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(530, 500));
        contentPanel.setMinimumSize(new java.awt.Dimension(530, 500));
        contentPanel.setPreferredSize(new java.awt.Dimension(530, 500));
        contentPanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(65, 40, 107));
        jPanel1.setLayout(null);
        contentPanel.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 10);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visitor's Information");
        contentPanel.add(jLabel1);
        jLabel1.setBounds(10, 30, 510, 30);

        jPanel2.setBackground(new java.awt.Color(65, 40, 107));
        jPanel2.setLayout(null);
        contentPanel.add(jPanel2);
        jPanel2.setBounds(10, 70, 510, 10);

        jPanel3.setBackground(new java.awt.Color(65, 40, 107));
        jPanel3.setLayout(null);
        contentPanel.add(jPanel3);
        jPanel3.setBounds(400, 30, 120, 30);

        jPanel4.setBackground(new java.awt.Color(65, 40, 107));
        jPanel4.setLayout(null);
        contentPanel.add(jPanel4);
        jPanel4.setBounds(10, 30, 120, 30);

        jLabel5.setText("Kids :");
        contentPanel.add(jLabel5);
        jLabel5.setBounds(170, 140, 80, 16);

        kidVisitor.setText("0");
        contentPanel.add(kidVisitor);
        kidVisitor.setBounds(270, 140, 7, 16);

        jLabel6.setText("Total Visitor's according to age ");
        contentPanel.add(jLabel6);
        jLabel6.setBounds(161, 100, 210, 16);

        jLabel3.setText("Teenager :");
        contentPanel.add(jLabel3);
        jLabel3.setBounds(170, 180, 90, 16);

        teenVisitor.setText("0");
        contentPanel.add(teenVisitor);
        teenVisitor.setBounds(270, 180, 7, 16);

        jLabel7.setText("Adult :");
        contentPanel.add(jLabel7);
        jLabel7.setBounds(170, 220, 50, 16);

        adultVisitor.setText("0");
        contentPanel.add(adultVisitor);
        adultVisitor.setBounds(270, 220, 7, 16);

        getContentPane().add(contentPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    public static void main(String args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new queryVisitorInfoPanel(queryString).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adultVisitor;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel contentPanel1;
    private javax.swing.JTable dataTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kidVisitor;
    private javax.swing.JScrollPane tableScrollPanel1;
    private javax.swing.JLabel teenVisitor;
    // End of variables declaration//GEN-END:variables

    public void main(String[] args) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

   
}
