package Mainpackage;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JPanel;
import MenuItems.*;

public class TheFrame extends javax.swing.JFrame {

    //menuState is a variable which will determine the current screen on refreshing operation
    int menuState = 0;
    //for storing the desired menu item object on refreshing operation
    JPanel desiredItem;

    private void setmenuItemWindow(JPanel menuItemWindow) {
        /*This function is created for removing all contents of current jpanel
        and set object of another panel. By this, we will be able to change 
        windows dynamically.*/
        this.menuItemWindow.removeAll();
        this.menuItemWindow.setSize(menuItemWindow.getSize());
        this.menuItemWindow.add(menuItemWindow);
        this.menuItemWindow.repaint();
        this.menuItemWindow.revalidate();
    }

    private void highlightMenuButton(JPanel menuButton) {
        //default menu panel RGB color
        int defR = 65;
        int defG = 40;
        int defB = 107;
        visitorInfoButton.setBackground(new Color(defR, defG, defB));
        parkingInfoButton.setBackground(new Color(defR, defG, defB));
        visitorFeedbackButton.setBackground(new Color(defR, defG, defB));
        staffInfoButton.setBackground(new Color(defR, defG, defB));
        staffPaymentButton.setBackground(new Color(defR, defG, defB));
        regionInfoButton.setBackground(new Color(defR, defG, defB));
        entryTicketInfoButton.setBackground(new Color(defR, defG, defB));
        entryCounterButton.setBackground(new Color(defR, defG, defB));
        rideInfoButton.setBackground(new Color(defR, defG, defB));
        rideCounterButton.setBackground(new Color(defR, defG, defB));
        foodInfoButton.setBackground(new Color(defR, defG, defB));
        foodCounterButton.setBackground(new Color(defR, defG, defB));

        //highlighted menu panel RGB color 
        int hR = 85;
        int hG = 52;
        int hB = 141;
        menuButton.setBackground(new Color(hR, hG, hB));
    }

    public TheFrame() {
        initComponents();
        
        //Setting the icon image for the application
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/AppIcons/logo.png")));
        
        //setting the loading screen in the middle of the screen
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ApplicationWindow = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        visitorInfoButton = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        parkingInfoButton = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        visitorFeedbackButton = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        staffInfoButton = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        staffPaymentButton = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        regionInfoButton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        entryTicketInfoButton = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        entryCounterButton = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rideInfoButton = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        rideCounterButton = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        foodInfoButton = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        foodCounterButton = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        menuItemWindow = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Park Management System");
        setMinimumSize(new java.awt.Dimension(750, 450));
        setResizable(false);

        ApplicationWindow.setBackground(new java.awt.Color(204, 204, 255));
        ApplicationWindow.setForeground(new java.awt.Color(185, 185, 185));
        ApplicationWindow.setName(""); // NOI18N
        ApplicationWindow.setPreferredSize(new java.awt.Dimension(750, 500));
        ApplicationWindow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuPanel.setBackground(new java.awt.Color(65, 40, 107));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(85, 52, 141));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("VISITOR:");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, 30));

        menuPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 90));

        jPanel16.setBackground(new java.awt.Color(85, 52, 141));
        jPanel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STAFF:");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, 30));

        menuPanel.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 100, 60));

        jPanel15.setBackground(new java.awt.Color(85, 52, 141));
        jPanel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" REGION:");
        jPanel15.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        menuPanel.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 100, 30));

        jPanel24.setBackground(new java.awt.Color(85, 52, 141));
        jPanel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" ENTRY:");
        jPanel24.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        menuPanel.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 100, 60));

        jPanel26.setBackground(new java.awt.Color(85, 52, 141));
        jPanel26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" RIDE:");
        jPanel26.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        menuPanel.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 100, 60));

        jPanel22.setBackground(new java.awt.Color(85, 52, 141));
        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" FOOD:");
        jPanel22.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        menuPanel.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 100, 60));

        visitorInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        visitorInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorInfoButtonMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" Visitor's Info");

        javax.swing.GroupLayout visitorInfoButtonLayout = new javax.swing.GroupLayout(visitorInfoButton);
        visitorInfoButton.setLayout(visitorInfoButtonLayout);
        visitorInfoButtonLayout.setHorizontalGroup(
            visitorInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitorInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        visitorInfoButtonLayout.setVerticalGroup(
            visitorInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visitorInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(visitorInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        parkingInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        parkingInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                parkingInfoButtonMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" Parking Info");

        javax.swing.GroupLayout parkingInfoButtonLayout = new javax.swing.GroupLayout(parkingInfoButton);
        parkingInfoButton.setLayout(parkingInfoButtonLayout);
        parkingInfoButtonLayout.setHorizontalGroup(
            parkingInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkingInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        parkingInfoButtonLayout.setVerticalGroup(
            parkingInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        menuPanel.add(parkingInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));

        visitorFeedbackButton.setBackground(new java.awt.Color(65, 40, 107));
        visitorFeedbackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                visitorFeedbackButtonMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(" Feedback");

        javax.swing.GroupLayout visitorFeedbackButtonLayout = new javax.swing.GroupLayout(visitorFeedbackButton);
        visitorFeedbackButton.setLayout(visitorFeedbackButtonLayout);
        visitorFeedbackButtonLayout.setHorizontalGroup(
            visitorFeedbackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(visitorFeedbackButtonLayout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        visitorFeedbackButtonLayout.setVerticalGroup(
            visitorFeedbackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, visitorFeedbackButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(visitorFeedbackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 120, -1));

        staffInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        staffInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffInfoButtonMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(" Staff's Info");

        javax.swing.GroupLayout staffInfoButtonLayout = new javax.swing.GroupLayout(staffInfoButton);
        staffInfoButton.setLayout(staffInfoButtonLayout);
        staffInfoButtonLayout.setHorizontalGroup(
            staffInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        staffInfoButtonLayout.setVerticalGroup(
            staffInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(staffInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, -1));

        staffPaymentButton.setBackground(new java.awt.Color(65, 40, 107));
        staffPaymentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffPaymentButtonMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Staff's Payout");

        javax.swing.GroupLayout staffPaymentButtonLayout = new javax.swing.GroupLayout(staffPaymentButton);
        staffPaymentButton.setLayout(staffPaymentButtonLayout);
        staffPaymentButtonLayout.setHorizontalGroup(
            staffPaymentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        staffPaymentButtonLayout.setVerticalGroup(
            staffPaymentButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffPaymentButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(staffPaymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 120, -1));

        regionInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        regionInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                regionInfoButtonMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Region Info");

        javax.swing.GroupLayout regionInfoButtonLayout = new javax.swing.GroupLayout(regionInfoButton);
        regionInfoButton.setLayout(regionInfoButtonLayout);
        regionInfoButtonLayout.setHorizontalGroup(
            regionInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regionInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );
        regionInfoButtonLayout.setVerticalGroup(
            regionInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regionInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(regionInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 120, -1));

        entryTicketInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        entryTicketInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryTicketInfoButtonMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" Ticket Info");

        javax.swing.GroupLayout entryTicketInfoButtonLayout = new javax.swing.GroupLayout(entryTicketInfoButton);
        entryTicketInfoButton.setLayout(entryTicketInfoButtonLayout);
        entryTicketInfoButtonLayout.setHorizontalGroup(
            entryTicketInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryTicketInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        entryTicketInfoButtonLayout.setVerticalGroup(
            entryTicketInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryTicketInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(entryTicketInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 120, -1));

        entryCounterButton.setBackground(new java.awt.Color(65, 40, 107));
        entryCounterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                entryCounterButtonMousePressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" Ticket Counter");

        javax.swing.GroupLayout entryCounterButtonLayout = new javax.swing.GroupLayout(entryCounterButton);
        entryCounterButton.setLayout(entryCounterButtonLayout);
        entryCounterButtonLayout.setHorizontalGroup(
            entryCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        entryCounterButtonLayout.setVerticalGroup(
            entryCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entryCounterButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(entryCounterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 120, -1));

        rideInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        rideInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rideInfoButtonMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(" Ride Info");

        javax.swing.GroupLayout rideInfoButtonLayout = new javax.swing.GroupLayout(rideInfoButton);
        rideInfoButton.setLayout(rideInfoButtonLayout);
        rideInfoButtonLayout.setHorizontalGroup(
            rideInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rideInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        rideInfoButtonLayout.setVerticalGroup(
            rideInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rideInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(rideInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 120, -1));

        rideCounterButton.setBackground(new java.awt.Color(65, 40, 107));
        rideCounterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rideCounterButtonMousePressed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(" Ticket Counter");

        javax.swing.GroupLayout rideCounterButtonLayout = new javax.swing.GroupLayout(rideCounterButton);
        rideCounterButton.setLayout(rideCounterButtonLayout);
        rideCounterButtonLayout.setHorizontalGroup(
            rideCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rideCounterButtonLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 4, Short.MAX_VALUE))
        );
        rideCounterButtonLayout.setVerticalGroup(
            rideCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rideCounterButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(rideCounterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 120, -1));

        foodInfoButton.setBackground(new java.awt.Color(65, 40, 107));
        foodInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                foodInfoButtonMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" Food Info");

        javax.swing.GroupLayout foodInfoButtonLayout = new javax.swing.GroupLayout(foodInfoButton);
        foodInfoButton.setLayout(foodInfoButtonLayout);
        foodInfoButtonLayout.setHorizontalGroup(
            foodInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodInfoButtonLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        foodInfoButtonLayout.setVerticalGroup(
            foodInfoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodInfoButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(foodInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, -1));

        foodCounterButton.setBackground(new java.awt.Color(65, 40, 107));
        foodCounterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                foodCounterButtonMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Food Counter");

        javax.swing.GroupLayout foodCounterButtonLayout = new javax.swing.GroupLayout(foodCounterButton);
        foodCounterButton.setLayout(foodCounterButtonLayout);
        foodCounterButtonLayout.setHorizontalGroup(
            foodCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodCounterButtonLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        foodCounterButtonLayout.setVerticalGroup(
            foodCounterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodCounterButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuPanel.add(foodCounterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 120, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 40));

        refreshButton.setBackground(new java.awt.Color(65, 40, 107));
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        menuPanel.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 90, 30));

        ApplicationWindow.add(menuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 500));

        menuItemWindow.setBackground(new java.awt.Color(153, 255, 0));
        menuItemWindow.setMaximumSize(new java.awt.Dimension(530, 450));
        menuItemWindow.setMinimumSize(new java.awt.Dimension(530, 450));
        menuItemWindow.setLayout(new java.awt.CardLayout());

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppIcons/defHomeImage.png"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(530, 500));
        jLabel19.setMinimumSize(new java.awt.Dimension(530, 500));
        jLabel19.setPreferredSize(new java.awt.Dimension(530, 500));
        menuItemWindow.add(jLabel19, "card2");

        ApplicationWindow.add(menuItemWindow, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 530, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ApplicationWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ApplicationWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitorInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorInfoButtonMousePressed
        highlightMenuButton(visitorInfoButton);
        
        //showing the following menu item after the mouse click
        visitorInfoPanel ob = new visitorInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 1;
    }//GEN-LAST:event_visitorInfoButtonMousePressed

    private void parkingInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkingInfoButtonMousePressed
        highlightMenuButton(parkingInfoButton);
        
        //showing the following menu item after the mouse click
        parkingInfoPanel ob = new parkingInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 2;
    }//GEN-LAST:event_parkingInfoButtonMousePressed

    private void visitorFeedbackButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visitorFeedbackButtonMousePressed
        highlightMenuButton(visitorFeedbackButton);
        
        //showing the following menu item after the mouse click
        visitorFeedbackPanel ob = new visitorFeedbackPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 3;
    }//GEN-LAST:event_visitorFeedbackButtonMousePressed

    private void staffInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffInfoButtonMousePressed
        highlightMenuButton(staffInfoButton);
        
        //showing the following menu item after the mouse click
        staffInfoPanel ob = new staffInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 4;
    }//GEN-LAST:event_staffInfoButtonMousePressed

    private void staffPaymentButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffPaymentButtonMousePressed
        highlightMenuButton(staffPaymentButton);
        
        //showing the following menu item after the mouse click
        staffPaymentPanel ob = new staffPaymentPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 5;
    }//GEN-LAST:event_staffPaymentButtonMousePressed

    private void regionInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regionInfoButtonMousePressed
        highlightMenuButton(regionInfoButton);
        
        //showing the following menu item after the mouse click
        regionInfoPanel ob = new regionInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 6;
    }//GEN-LAST:event_regionInfoButtonMousePressed

    private void entryTicketInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryTicketInfoButtonMousePressed
        highlightMenuButton(entryTicketInfoButton);
        
        //showing the following menu item after the mouse click
        entryTicketInfoPanel ob = new entryTicketInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 7;
    }//GEN-LAST:event_entryTicketInfoButtonMousePressed

    private void entryCounterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryCounterButtonMousePressed
        highlightMenuButton(entryCounterButton);
        
        //showing the following menu item after the mouse click
        entryCounterPanel ob = new entryCounterPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 8;
    }//GEN-LAST:event_entryCounterButtonMousePressed

    private void rideInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rideInfoButtonMousePressed
        highlightMenuButton(rideInfoButton);
        
        //showing the following menu item after the mouse click
        rideInfoPanel ob = new rideInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 9;
    }//GEN-LAST:event_rideInfoButtonMousePressed

    private void rideCounterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rideCounterButtonMousePressed
        highlightMenuButton(rideCounterButton);
        
        //showing the following menu item after the mouse click
        rideCounterPanel ob = new rideCounterPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 10;
    }//GEN-LAST:event_rideCounterButtonMousePressed

    private void foodInfoButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodInfoButtonMousePressed
        highlightMenuButton(foodInfoButton);
        
        //showing the following menu item after the mouse click
        foodInfoPanel ob = new foodInfoPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 11;
    }//GEN-LAST:event_foodInfoButtonMousePressed

    private void foodCounterButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foodCounterButtonMousePressed
        highlightMenuButton(foodCounterButton);
        
        //showing the following menu item after the mouse click
        foodCounterPanel ob = new foodCounterPanel();
        menuItemWindow.removeAll();
        setmenuItemWindow(ob);
        menuState = 12;
    }//GEN-LAST:event_foodCounterButtonMousePressed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        //choosing desired menu items based on menu state
        if (menuState == 1) {
            visitorInfoPanel ob = new visitorInfoPanel();
            desiredItem = ob;
        } else if (menuState == 2) {
            parkingInfoPanel ob = new parkingInfoPanel();
            desiredItem = ob;
        } else if (menuState == 3) {
            visitorFeedbackPanel ob = new visitorFeedbackPanel();
            desiredItem = ob;
        } else if (menuState == 4) {
            staffInfoPanel ob = new staffInfoPanel();
            desiredItem = ob;
        } else if (menuState == 5) {
            staffPaymentPanel ob = new staffPaymentPanel();
            desiredItem = ob;
        } else if (menuState == 6) {
            regionInfoPanel ob = new regionInfoPanel();
            desiredItem = ob;
        } else if (menuState == 7) {
            entryTicketInfoPanel ob = new entryTicketInfoPanel();
            desiredItem = ob;
        } else if (menuState == 8) {
            entryCounterPanel ob = new entryCounterPanel();
            desiredItem = ob;
        } else if (menuState == 9) {
            rideInfoPanel ob = new rideInfoPanel();
            desiredItem = ob;
        } else if (menuState == 10) {
            rideCounterPanel ob = new rideCounterPanel();
            desiredItem = ob;
        } else if (menuState == 11) {
            foodInfoPanel ob = new foodInfoPanel();
            desiredItem = ob;
        } else if (menuState == 12) {
            foodCounterPanel ob = new foodCounterPanel();
            desiredItem = ob;
        }

        //drawing the desired menu item on refresh
        if (menuState != 0) {
            menuItemWindow.removeAll();
            setmenuItemWindow(desiredItem);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ApplicationWindow;
    private javax.swing.JPanel entryCounterButton;
    private javax.swing.JPanel entryTicketInfoButton;
    private javax.swing.JPanel foodCounterButton;
    private javax.swing.JPanel foodInfoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel menuItemWindow;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel parkingInfoButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JPanel regionInfoButton;
    private javax.swing.JPanel rideCounterButton;
    private javax.swing.JPanel rideInfoButton;
    private javax.swing.JPanel staffInfoButton;
    private javax.swing.JPanel staffPaymentButton;
    private javax.swing.JPanel visitorFeedbackButton;
    private javax.swing.JPanel visitorInfoButton;
    // End of variables declaration//GEN-END:variables
}
